import type { EventSource } from '@/data/event-source';
import type { StockholmEvent } from '@/types/event';

/**
 * Serves the pre-built event snapshot generated by the pipeline
 * (`pipeline/ -> npm run snapshot`) when it is bundled into the app.
 *
 * EAS builds exclude the snapshot (see `.easignore`) to save ~8 MB — the app
 * then relies on `EXPO_PUBLIC_SNAPSHOT_URL` (remote) with the mock source as
 * last resort. Local dev and the web export keep the file and serve it here.
 *
 * Loaded via `require.context` rather than a direct `require` so Metro can
 * resolve the module graph even when the JSON file is not present.
 */
type SnapshotFile = { events: StockholmEvent[]; attribution?: string };

type FileContext = {
  keys(): string[];
  (key: string): unknown;
};

declare const require: {
  context(directory: string, useSubdirectories?: boolean, regExp?: RegExp): FileContext;
};

const SNAPSHOT_KEY = './events.snapshot.json';

function loadSnapshot(): SnapshotFile | null {
  try {
    // Metro evaluates require.context statically: the directory and RegExp
    // arguments must be inline literals, not variables.
    const context = require.context('./', false, /^\.\/events\.snapshot\.json$/);
    const key = context.keys().find((candidate) => candidate === SNAPSHOT_KEY);
    if (!key) return null;
    return context(key) as SnapshotFile;
  } catch {
    return null;
  }
}

const snapshot = loadSnapshot();
const ATTRIBUTION = snapshot?.attribution ?? null;

function loadEvents(): StockholmEvent[] {
  const all = snapshot?.events ?? [];
  const now = Date.now();
  return all
    .filter((event) => new Date(event.endsAt ?? event.startsAt).getTime() >= now)
    .sort((a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime());
}

const EVENTS = loadEvents();

export class StaticEventSource implements EventSource {
  readonly attribution = ATTRIBUTION;

  get size(): number {
    return EVENTS.length;
  }

  async list(): Promise<StockholmEvent[]> {
    return EVENTS;
  }

  async getById(id: string): Promise<StockholmEvent | null> {
    return EVENTS.find((event) => event.id === id) ?? null;
  }
}
