import type { EventSource } from '@/data/event-source';
import type { StockholmEvent } from '@/types/event';

/**
 * Serves the pre-built event snapshot generated by the pipeline
 * (`pipeline/ -> npm run snapshot`). Real, image-enriched data with no runtime
 * network calls or database. Regenerate the snapshot to refresh (daily-cron
 * model); swap this for a remote/DB-backed source later without UI changes.
 *
 * Data: Visit Stockholm (Stockholm Business Region), CC BY 4.0.
 *
 * Loaded via `require` (Metro bundles it as an asset) so the type-checker
 * doesn't pay the cost of inferring the whole JSON literal on every run.
 */
type SnapshotFile = { events: StockholmEvent[]; attribution?: string };

// eslint-disable-next-line @typescript-eslint/no-require-imports
const snapshot = require('./events.snapshot.json') as SnapshotFile;

const ATTRIBUTION = snapshot.attribution ?? null;

function loadEvents(): StockholmEvent[] {
  const all = snapshot.events ?? [];
  const now = Date.now();
  return all
    .filter((event) => new Date(event.endsAt ?? event.startsAt).getTime() >= now)
    .sort((a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime());
}

const EVENTS = loadEvents();

export class StaticEventSource implements EventSource {
  readonly attribution = ATTRIBUTION;

  get size(): number {
    return EVENTS.length;
  }

  async list(): Promise<StockholmEvent[]> {
    return EVENTS;
  }

  async getById(id: string): Promise<StockholmEvent | null> {
    return EVENTS.find((event) => event.id === id) ?? null;
  }
}
